<?php
    require_once 'src/App/components/Header.php';
?>
    <section class="advantages section">
        <div class="container">
            <div class="advantages__inner">
                <h1 class="advantages__title title section__title">Преимущества</h1>
                <div class="advantages__list">
                    <div class="advantages__item">
                        <img class="advantages__item-img" src="https://avatars.steamstatic.com/014d4e7cd2cbf2068f180626fc0b39680ee8145b_full.jpg" alt="">
                        <div class="advantages__item-content">
                            <h3 class="advantages__item-title">Media awdawd</h3>
                            <p class="advantages__item-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt tempora explicabo cumque voluptatum est repellat et, sequi doloribus officia, neque, fuga beatae alias laudantium hic omnis error doloremque? Voluptas, tempora!</p>
                        </div>
                    </div>
                    <div class="advantages__item">
                        <img class="advantages__item-img" src="https://avatars.steamstatic.com/014d4e7cd2cbf2068f180626fc0b39680ee8145b_full.jpg" alt="">
                        <div class="advantages__item-content">
                            <h3 class="advantages__item-title">Media awdawd</h3>
                            <p class="advantages__item-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt tempora explicabo cumque voluptatum est repellat et, sequi doloribus officia, neque, fuga beatae alias laudantium hic omnis error doloremque? Voluptas, tempora!</p>
                        </div>
                    </div>
                    <div class="advantages__item">
                        <img class="advantages__item-img" src="https://avatars.steamstatic.com/014d4e7cd2cbf2068f180626fc0b39680ee8145b_full.jpg" alt="">
                        <div class="advantages__item-content">
                            <h3 class="advantages__item-title">Media awdawd</h3>
                            <p class="advantages__item-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt tempora explicabo cumque voluptatum est repellat et, sequi doloribus officia, neque, fuga beatae alias laudantium hic omnis error doloremque? Voluptas, tempora!</p>
                        </div>
                    </div>
                    <div class="advantages__item">
                        <img class="advantages__item-img" src="https://avatars.steamstatic.com/014d4e7cd2cbf2068f180626fc0b39680ee8145b_full.jpg" alt="">
                        <div class="advantages__item-content">
                            <h3 class="advantages__item-title">Media awdawd</h3>
                            <p class="advantages__item-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt tempora explicabo cumque voluptatum est repellat et, sequi doloribus officia, neque, fuga beatae alias laudantium hic omnis error doloremque? Voluptas, tempora!</p>
                        </div>
                    </div>
                </div>
                <div class="advantages__btn">
                    <a href="<?= $url->make('index') ?>" class="btn btn__green">Заказать</a>
                </div>
            </div>
        </div>
    </section>


</body>
</html>