<?php
    require_once 'src/App/components/Header.php';
?>

<section class="contacts section">
    <div class="container">
        <div class="contacts__inner">
            <h1 class="contacts__title title section__title">Контакты</h1>
            <div class="contacts__content">
                <div class="contacts__map"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A2ae19ba687d9f60a680b863cbda602e405e5e69be3a1a9c8477e756c07b8187a&amp;width=350&amp;height=443&amp;lang=ru_RU&amp;scroll=true"></script></div>
                <div class="contacts__info">
                    <h4 class="contacts__info-adress">г. Севастополь, ПОР 42Б</h4>
                    <h5 class="contacts__info-phone">+7(978) 051-10-50</h5>
                    <h6 class="contacts__info-email">info@marketingl.su</h6>
                    <h6 class="contacts__info-name">Мессенджеры</h6>
                    <div class="contacts-messagers">
                        <div class="contacts-messagers__item">
                            <img class="contacts-messagers__img" src="/images/viber.png" alt="">
                            <strong class="contacts-messagers__name">Viber</strong>
                        </div>
                        <div class="contacts-messagers__item">
                            <img class="contacts-messagers__img" src="/images/whatsapp.png" alt="">
                            <strong class="contacts-messagers__name">WhatsApp</strong>
                        </div>
                    </div>
                    <div class="contacts__info-messager">
                        Номер телефона для мессенджера +7 (978) 051-10-50
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>